### ISSUE TITLE
Please supply some documentation for the software (how it compile for Windows and how to use it)

### ISSUE THREAD

**Issue by mesmariusz** [r1me/TapeXUM#5]
Please publicate some documentation regarding the software. 
I can see only some .pas sources, unfortunately I don't practice this language.

Could you please to be so kind and publish somewhere the guide step by step:

- which compiler could be used
- how to compile each application step by step
- how to use it

Generaly short documentation for supplied software could be very usefull. 

This project is very very interesting but really poor documented (maybe available just a professional coders).

This project looks to be so great that it could be really too bad to waste it.

Thank you and best regards
Mariusz

**Comment by r1me** [comment]
This repository contains only two applications that were made in Delphi Community Edition, these are: single button installer for 64-bit Windows, and a tapfit tool (datassette head fit). The actual code for OpenCBM library, original ZoomTape tools, firmware is [here](https://github.com/r1me/OpenCBM), and in short words is a OpenCBM but slightly modified to support new ZoomTape hardware aka TapeXUM. I will add short description of each ZoomTape tool, since original website is [down](https://web.archive.org/web/20160707132841/http://zoomtape.de.vu/), but that's it.

**Comment by mesmariusz** [comment]
Hi again. 

1). When I try to build the one button installer, I got this:

![image](https://user-images.githubusercontent.com/3919173/177846094-35e7dacc-8223-4a92-af7a-662b5a806858.png)
![image](https://user-images.githubusercontent.com/3919173/177846058-6acf5a73-c73c-4007-9047-34708971cd6b.png)


2). When I try to build tapfit, I got this:

![image](https://user-images.githubusercontent.com/3919173/177845980-342e8f12-8cce-4ac2-871b-02249a3837d1.png)

So build with success.

So If I try to run, then I see:

![image](https://user-images.githubusercontent.com/3919173/177846236-fa32768e-57af-4eac-9b58-5f0b679a9c9c.png)

So now I think I should install OpenCBM modified, but I can't see any download links here:
[https://web.archive.org/web/20160707132841/http://zoomtape.de.vu/](https://web.archive.org/web/20160707132841/http://zoomtape.de.vu/)

O, I see it's probably here:
https://github.com/r1me/OpenCBM

But may I find it somewhere compiled For Win64 (or Win32) ?
Or to get some fast instructions how to compile it?

Im not a programmer / code writer, but as You can see, I'm patiently trying to get working result :-)

**Comment by r1me** [comment]
You don't have to build a single app, precompiled binaries were always available in [releases section](https://github.com/r1me/TapeXUM/releases).

**Comment by mesmariusz** [comment]
Thank you. 
I didn't saw it ;-)
