### ISSUE TITLE
cap and tap files seems to be OK, but games are not succesfully loaded in Vice

### ISSUE THREAD

**Issue by mesmariusz** [r1me/TapeXUM#6]
Hi. 

I just run the tapeXum for the first time. Everything seems to work correctly. 
I take one of my tapes. At first I checked it on my real C64 and Datasette. 
Games are loading correctlu, without errors then run succesfully. 

So I decided to grab it using TapeXUM. 

At fiirst I created the .cap file:

tapread -c64pal kaseta.cap

then i converted it to .tap file:

cap2tap kaseta.cap kaseta.tap

Loaded into Vice .tap file seems to be correct:

![image](https://user-images.githubusercontent.com/3919173/177885202-23cd4223-bae0-4161-830d-1df7cc8a2005.png)

But then notheing can be run properly:

![Jzy3q6Ojmp](https://user-images.githubusercontent.com/3919173/177885903-980d35b1-d894-4897-b02f-7ce8013b0de6.gif)

Any ideas ?

Could you please investigate my output files then ? Maybe @ your Vice it will work then ?

https://drive.google.com/drive/folders/12xA4-uFq5N9pycovz5vFrBZfL38H6PY9?usp=sharing

Thank you and best regards
Mariusz

**Comment by r1me** [comment]
TAP is a raw tape format, it is a digital representation of analog data that was stored on tape (as opposite to T64 which is a program file container). Vice can only read original and turbo data headers from TAP and display them on the list. If the actual data is in turbo format, the autostart feature in Vice will fail. You have to emulate real environment by attaching a turbo cartridge/kernal and then load data, or by loading a compatible loader first. There are like 100 or so, documented type of loaders. Also your file most likely starts from them middle of other program - not beginning of a tape, so there is a buggy header with enormous pause that had to be fixed with a TAPClean (sounds like a bug in cap2tap). But nevertheless, a CRC of INDIANA JONES 1 is bad, resulting in load error. Head fit was "okayish", but clearly your tape is old, you can hear a loss of data. Before creating a dump of old tape, I recommend setting head fit on C64 until data can be loaded correctly, then switch datassette to TapeXUM setup.
![indiana](https://user-images.githubusercontent.com/13695767/179027024-992cb102-59b5-4cae-a1ed-6f3c1eef97b2.png)

**Comment by mesmariusz** [comment]
Hmm... As I mentioned, The datasette was previously connected to real C64 and, head fitted, (turbo format) games loaded succesfully. Then I swithed the datasette into tapeXum.

But maybe I will try to run black Box 3 or 4 on Vice first. But at first I need to find how to do it. And to find. crt files of black boxes if there are present somewhere. 

Edit:

It looks like that:

https://i.imgur.com/B5Zstel.gif
